name: test-jest-github-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-jest-github-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      # - run: |
      #     git fetch --no-tags origin $GITHUB_BASE_REF
      #     git checkout -t origin/$GITHUB_BASE_REF
      #     git checkout ${{ github.event.pull_request.head.sha }}
      - name: Install NPM packages
        uses: bahmutov/npm-install@v1
      - uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'yarn test'
