name: test-jest-github-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-jest-github-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git fetch --no-tags origin $GITHUB_BASE_REF
          git checkout -t origin/$GITHUB_BASE_REF
          git checkout ${{ github.event.pull_request.head.sha }}
      - name: Install NPM packages
        uses: bahmutov/npm-install@v1
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: csv
      - run: |
          echo ${{ steps.files.outputs.all }}
      - name: get modified codes
        id: modified_codes
        run: |
          modified_codes=""
          mapfile -d ',' -t modified_files < <(printf '%s,' '${{ steps.files.outputs.all }}')
          for code in "${modified_files[@]}"; do
            if [[ $code =~ \.test\.ts ]] ; then
              modified_codes="$modified_codes $(echo $code | sed 's/\.test//')"
            fi
          done
          echo "$modified_codes"
          echo ::set-output name=codes::"$modified_codes"
      - run: |
          echo ${{ steps.modified_codes.outputs.codes }}
      - name: Run Tests
        run: yarn test --coverage --json --outputFile=/home/runner/work/test-jest-github-action/test-jest-github-action/jest.results.json --collectCoverageFrom='[${{steps.modified_codes.outputs.codes}}]'
      - uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'echo done'
